[project]
name = "spec-kit-mcp"
version = "0.0.2"
description = "Model Context Protocol server for Specify spec-driven development tools"
requires-python = ">=3.11"
dependencies = [
    "mcp",
    "typer",
    "rich",
    "httpx",
    "platformdirs",
    "readchar",
]

[project.scripts]
spec-kit-mcp = "spec_kit_mcp.server:main"
specify = "spec_kit_mcp.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/spec_kit_mcp"]